$:
  vscode:
    - docker:
        build: .ide/Dockerfile
      runner:
        cpus: 16
        tags: cnb:arch:amd64:gpu
      services:
        - vscode
        - docker
      stages:
        - name: start ollama
          script: nohup ollama serve >/dev/null 2>&1 &
        - name: Temporary Public Network url
          script: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 443 -R0:localhost:11434 qr@free.pinggy.io 2>/dev/null | grep -m 1 '^https://.*pinggy.link' > tempurl.txt
            git add .
            git commit -m "update tempurl"
            git push