$:
  vscode:
    - docker:
        image: docker.cnb.cool/anyexyz/ollama/env/dockerfile-caches:6ebc4fc1497ed8b34b38b4201fd9013977a40cd1
      runner:
        cpus: 16
        tags: cnb:arch:amd64:gpu
      services:
        - vscode
        - docker
      stages:
        - name: start ollama
          script: nohup ollama serve >/dev/null 2>&1 &