$:
  vscode:
    - docker:
        build: .ide/Dockerfile
      runner:
        cpus: 16
        tags: cnb:arch:amd64:gpu
      services:
        - vscode
        - docker
      stages:
        - name: start ollama
          script: nohup ollama serve >/dev/null 2>&1 &
        - name: starturl
          script: ssh -p 443 -R0:localhost:11434 qr@free.pinggy.io
        - name: start_yes
          script: yes
